### ISSUE TITLE
.gitattributes

### ISSUE THREAD

**Issue by fwalch** [mauke/unibilium#13]
Github supports a `.gitattributes` file to [exclude certain files from release tarballs](https://github.com/junegunn/vader.vim/blob/master/.gitattributes). Not sure if this is interesting for you at all, but maybe you want to add `maint.mk` in there and get rid of `ifneq ($(wildcard .git),)`. Just wanted to let you know, feel free to close this issue.

**Comment by mauke** [comment]
Well, this has been solved in a different way now (see #20). In any case, the presence of `.git` doesn't affect the build anymore.
