### ISSUE TITLE
extalllen and extstrslen vs extofflen

### ISSUE THREAD

**Issue by nhooyr** [mauke/unibilium#17]
I was going through the source to understand the extended capability format. I'm very confused on how it works. I'm writing a terminfo parsing library for go https://github.com/nhooyr/terminfo.

https://github.com/mauke/unibilium/blob/master/unibilium.c#L312

```c
DEL_FAIL_IF(extofflen != extalllen + extstrslen, EINVAL, t);
```

How is that true? Why would the `extalllen + extstrslen` need to be equal to the `extofflen`? I didn't see any check like this in the ncurses src. And if it is so, then later on in the code, why do this:

```c
const char *const tbl1 = p + extstrslen * 2 + extalllen * 2;
```

If `extstrslen + extalllen = extofflen`. Then `extstrslen * 2 + extalllen * 2 = extofflen * 2`.

So the above code can be simplified to:

```c
const char *const tbl1 = p + extofflen * 2;
```

And why is `extofflen` even there if you can compute its value by adding `extstrslen + extalllen`? According to term(5), it is the size of the extended table in bytes but we're using the 5th short for that, `exttablsz`. Ncurses doesn't even use `extofflen` after declaring it. Whats the point of `extofflen`?

**Comment by mauke** [comment]
Have a look at https://github.com/mauke/unibilium/blob/master/secret/terminfo.pod#extended-capabilities. I need to reread my own code to answer more.

**Comment by mauke** [comment]
After rereading my notes, I believe the above link answers all your questions. As for why `extofflen` is there: I have no idea; I didn't come up with the file format. Because it's so weird (and the ncurses code for reading terminfo doesn't use it), I tried to avoid it as well. That's why it's only used in one sanity check.

**Comment by nhooyr** [comment]
Yea I was able to implement it, thanks.
