### ISSUE TITLE
Unibilium fails in Konsole?

### ISSUE THREAD

**Issue by mgajda** [mauke/unibilium#19]
When I used Unibilium-based Neovim in Gnome Terminal, it correctly detects color terminal.
When I use it in Konsole, it reveals an entirely monochrome interface.
I am not sure whether to file this bug against Unibilium or Konsole, but other programs (like Vim), correctly detect Konsole as the color terminal.

**Comment by mauke** [comment]
What does `echo $TERM` say in your konsole? What does `infocmp` output?

**Comment by mgajda** [comment]
```> echo $TERM
xterm

> infocmp
#	Reconstructed via infocmp from file: /lib/terminfo/x/xterm
xterm|xterm-debian|X11 terminal emulator,
	am, bce, km, mc5i, mir, msgr, npc, xenl,
	colors#8, cols#80, it#8, lines#24, pairs#64,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
	dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
	el1=\E[1K, flash=\E[?5h$<100/>\E[?5l, home=\E[H,
	hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
	il=\E[%p1%dL, il1=\E[L, ind=^J, indn=\E[%p1%dS,
	invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
	kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
	kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE,
	kbs=\177, kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC,
	kcuu1=\EOA, kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP,
	kf10=\E[21~, kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P,
	kf14=\E[1;2Q, kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~,
	kf18=\E[17;2~, kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~,
	kf21=\E[20;2~, kf22=\E[21;2~, kf23=\E[23;2~,
	kf24=\E[24;2~, kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R,
	kf28=\E[1;5S, kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~,
	kf31=\E[18;5~, kf32=\E[19;5~, kf33=\E[20;5~,
	kf34=\E[21;5~, kf35=\E[23;5~, kf36=\E[24;5~,
	kf37=\E[1;6P, kf38=\E[1;6Q, kf39=\E[1;6R, kf4=\EOS,
	kf40=\E[1;6S, kf41=\E[15;6~, kf42=\E[17;6~,
	kf43=\E[18;6~, kf44=\E[19;6~, kf45=\E[20;6~,
	kf46=\E[21;6~, kf47=\E[23;6~, kf48=\E[24;6~,
	kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q, kf51=\E[1;3R,
	kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
	rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[27m,
	rmul=\E[24m, rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[4%p1%dm, setaf=\E[3%p1%dm,
	setb=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	setf=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
	smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m,
	smul=\E[4m, tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?1;2c, u9=\E[c, vpa=\E[%i%p1%dd,
```

**Comment by mauke** [comment]
According to that output, unibilium should detect 8 colors.

I built neovim-0.1.4 from source and ran it in konsole, but I can't reproduce the problem. Maybe try reporting it as a neovim bug?

Also, from the neovim source directory, I ran `./.deps/build/src/unibilium/tools/unibi-dump`, and it also detected 8 colors:
```
~/src/neovim-0.1.4 $ ./.deps/build/src/unibilium/tools/unibi-dump
Terminal name: xterm terminal emulator (X Window System)
Aliases: xterm

Boolean capabilities:
  auto_right_margin         / am
  eat_newline_glitch        / xenl
  has_meta_key              / km
  move_insert_mode          / mir
  move_standout_mode        / msgr
  prtr_silent               / mc5i
  no_pad_char               / npc
  back_color_erase          / bce
  backspaces_with_bs        / OTbs

Numeric capabilities:
  columns                   / cols       = 80
  init_tabs                 / it         = 8
  lines                     / lines      = 24
  max_colors                / colors     = 8
  max_pairs                 / pairs      = 64

...
```

**Comment by jdebp** [comment]
> I am not sure whether to file this bug against Unibilium or Konsole

Filing it against Neovim would have been the right thing to do.  However, it is far too late now.  There _were_ several ways in which one could have ended up in this situation, a year and a bit ago.  But a lot has happened since then.

Neovim's operation in this area is currently being further improved, and only one such way remains: setting `termguicolors` on a terminal that cannot do 24-bit RGB colour.  Neovim emits 24-bit SGR control sequences, the terminal does not recognize them, and everything comes out in black and white (technically: in the terminal's default colour pair).

This is not even the case for Konsole, however, which can do 24-bit RGB colour.

As demonstrated back in 2016, this is not a Unibilium problem.

**Comment by leonerd** [comment]
> Neovim emits 24-bit SGR control sequences, the terminal does not recognize them, and everything comes out in black and white (technically: in the terminal's default colour pair).

I would expect that most terminals that can support the 24bit SGR forms will also support query of those same forms. Neovim ought to be able to cope by querying the state after setting it the first time, to see if the terminal understood it; if not it can fallback on a simpler scheme.

**Comment by mauke** [comment]
This has stalled and I can't reproduce it. Maybe this was the same issue as https://github.com/neovim/neovim/issues/7003?
