### ISSUE TITLE
use of unsupported parameters make unibilium crash

### ISSUE THREAD

**Issue by teto** [mauke/unibilium#21]
For instance in neovim at some point I tried to register 
`(int)unibi_add_ext_str(ut, NULL, "\x1b[12;%s\x07");`
and it was enough to make unibilium crash (in unibi_format).

**Comment by teto** [comment]
btw is there any doc that describes the expect string format ?
I would like to be able to 
```
        data->params[0].p = "#8F8F00";
        unibi_out(ui, data->unibi_ext.set_cursor_color);
```
with set_cursor_color being registered as:
```
  data->unibi_ext.set_cursor_color = (int)unibi_add_ext_str(ut, NULL,
      "\x1b[12;%p1%s\x07");
```
yet it doesn't work, I wonder if the '#' is a special character :s

**Comment by mauke** [comment]
Yes, this area is unfortunately underdocumented (as in "not documented at all") in unibilium. See "Parameterized Strings" in `man terminfo` from your nearest ncurses distribution.

Basically `%s` pops a pointer off the internal data stack and prints it as a string. Your format string didn't push anything, so this dies with a null pointer dereference (which is admittedly terrible).

You should be able to do what you want by using `%p1%s` instead. `%p1` pushes the first parameter on the data stack.

**Comment by mauke** [comment]
I tried your second example and I can't reproduce the problem. I see `\x1b[12;#8F8F00\x07` being written.

**Comment by teto** [comment]
I looked at the code afterwards and was able to understand the format but this was not fun ^^
Forget about the example, I think I solved everything I had to :)
