### ISSUE TITLE
Strike-through

### ISSUE THREAD

**Issue by Nudin** [mauke/unibilium#22]
Seems like the strikethrough is missing, It is supported by xtermbased terms via `\033[9m ` – could you please add it? I'd need it for adding strikethough-support to neovim.

**Comment by leonerd** [comment]
unibilium is a terminfo database reader. It can only provide access to the information given by the terminfo databases.

Does there exist a standard field for strikethrough? I'm not aware of one. Do you have any detail on this?

**Comment by Nudin** [comment]
I seem to have misunderstood unibilium – **sorry**!
I'm not yet really familiar with terminfo… So when I call

    unibi_set_if_empty(ut, unibi_enter_underline_mode, "\x1b[4m");

unibilium queries terminfo database to see if underline is supported and if so, it prints out `\033[4m`. And since strikethrough is not supported by terminfo it isn't possible to add unibi_enter_strikethrough_mode analogous even if the terminal would be support `\033[9m`? Is this about right?

**Comment by leonerd** [comment]
Not quite. That call to `unibi_set_if_empty` is asking if `unibilium` happens to have a string, and if it doesn't, the gives it this default value anyway where `nvim` is just guessing what probably works.

Indeed there currently is not a `unibi_enter_strikethrough_mode`, so similar can't be done there.

I didn't want to categorically state that strikethrough definitely *isn't* supported by terminfo itself, because I don't happen to have a 100% sure source for that assertion, but my suspicion is that it is not.

**Comment by rofl0r** [comment]
also note that the terminfo format used by unibilium is ncurses-specific.
it does for example not work with [netbsd-curses](https://github.com/sabotage-linux/netbsd-curses/). so by using it you lock your users into a specific implementation.

**Comment by mauke** [comment]
Unfortunately there is no strike-through field in terminfo, so unibilium can't read it.

**Comment by mauke** [comment]
I just noticed that `xterm` actually has something for this in its terminfo entry:

- extended string capability `smxx` starts strike-through mode
- extended string capability `rmxx` returns from strike-through mode

It's a bit annoying to code, but you can do this with unibilium right now:

```c
#include <stdio.h>
#include <string.h>
#include "unibilium.h"

int main(void) {
    unibi_term *ut = unibi_from_env();
    const char *smxx = NULL, *rmxx = NULL;
    for (size_t i = 0, count = unibi_count_ext_str(ut); i < count; i++) {
        if (strcmp(unibi_get_ext_str_name(ut, i), "smxx") == 0) {
            smxx = unibi_get_ext_str(ut, i);
        } else if (strcmp(unibi_get_ext_str_name(ut, i), "rmxx") == 0) {
            rmxx = unibi_get_ext_str(ut, i);
        }
    }

    if (!smxx || !rmxx) {
        printf("Your terminal doesn't seem to support smxx and rmxx.\n");
        smxx = "";
        rmxx = "";
    }

    printf("Demo: %sfoo bar baz%s (if your terminal supports it)\n", smxx, rmxx);

    return 0;
}
```
