### ISSUE TITLE
Assertion error with terminfo 1.616

### ISSUE THREAD

**Issue by lbschenkel** [mauke/unibilium#24]
I have updated my terminal definitions to version 1.616 (ncurses-6.0-20170819). When `$TERM` is set to `tmux` (or `tmux-256color`) and invoke NeoVim, it crashes:

```
nvim: unibilium.c:735: unibi_get_str: Assertion `v > unibi_string_begin_ && v < unibi_string_end_' failed. 
zsh: abort (core dumped)  nvim
```

I can consistently reproduce this crash with NeoVim 0.2.0 in macOS and Ubuntu 16.04.

To reproduce:
1. download `terminfo.src.gz` from http://invisible-island.net/datafiles/current/terminfo.src.gz
2. decompress
3. compile it with `tic -x`
4. set `$TERM` to `tmux` (or `tmux-256color`, or `vte`, or `xterm`)
5. invoke `nvim` (**edit**: note my first comment below)

I have investigated a bit and this is what I found out:
- I have bisected the ncurses releases and I can confirm that the terminfo change that triggers the assertion error is the one from the release that I mentioned above.
- the assertion error **does not** happen when terminfo is compiled with `tic` (without `-x`)
- the assertion error **does** happen when terminfo is compiled with `tic -x`
- strangely enough, I found no difference in the output of `infocmp -x` between the previous version of terminfo sources (1.607) and the current one, both when compiling using `tic` and `tic -x`
- I realized that I can provoke the crash with other values of `$TERM` as well (`vte`, `xterm`, etc.)

In case it might be useful, I'm attaching a diff of the output of `infocmp -1x` of the capabilities when compiling terminfo 1.616 using `tic` (does not crash) and `tic -x` (does crash):

```
--- good.txt	2017-08-23 16:23:44.886527226 +0200
+++ bad.txt	2017-08-23 16:23:54.222425733 +0200
@@ -1,16 +1,21 @@
 #	Reconstructed via infocmp from file: /home/leonardo/.local/share/terminfo/t/tmux-256color
 tmux-256color|tmux with 256 colors,
+	OTbs,
+	OTpt,
 	am,
 	hs,
 	km,
 	mir,
 	msgr,
 	xenl,
+	AX,
+	G0,
 	colors#256,
 	cols#80,
 	it#8,
 	lines#24,
 	pairs#32767,
+	U8#1,
 	acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
 	bel=^G,
 	blink=\E[5m,
@@ -164,3 +169,65 @@
 	smul=\E[4m,
 	tbc=\E[3g,
 	tsl=\E]0;,
+	Cr=\E]112\007,
+	Cs=\E]12;%p1%s\007,
+	E0=\E(B,
+	Ms=\E]52;%p1%s;%p2%s\007,
+	S0=\E(%p1%c,
+	Se=\E[2 q,
+	Ss=\E[%p1%d q,
+	TS=\E]0;,
+	kDC3=\E[3;3~,
+	kDC4=\E[3;4~,
+	kDC5=\E[3;5~,
+	kDC6=\E[3;6~,
+	kDC7=\E[3;7~,
+	kDN=\E[1;2B,
+	kDN3=\E[1;3B,
+	kDN4=\E[1;4B,
+	kDN5=\E[1;5B,
+	kDN6=\E[1;6B,
+	kDN7=\E[1;7B,
+	kEND3=\E[1;3F,
+	kEND4=\E[1;4F,
+	kEND5=\E[1;5F,
+	kEND6=\E[1;6F,
+	kEND7=\E[1;7F,
+	kHOM3=\E[1;3H,
+	kHOM4=\E[1;4H,
+	kHOM5=\E[1;5H,
+	kHOM6=\E[1;6H,
+	kHOM7=\E[1;7H,
+	kIC3=\E[2;3~,
+	kIC4=\E[2;4~,
+	kIC5=\E[2;5~,
+	kIC6=\E[2;6~,
+	kIC7=\E[2;7~,
+	kLFT3=\E[1;3D,
+	kLFT4=\E[1;4D,
+	kLFT5=\E[1;5D,
+	kLFT6=\E[1;6D,
+	kLFT7=\E[1;7D,
+	kNXT3=\E[6;3~,
+	kNXT4=\E[6;4~,
+	kNXT5=\E[6;5~,
+	kNXT6=\E[6;6~,
+	kNXT7=\E[6;7~,
+	kPRV3=\E[5;3~,
+	kPRV4=\E[5;4~,
+	kPRV5=\E[5;5~,
+	kPRV6=\E[5;6~,
+	kPRV7=\E[5;7~,
+	kRIT3=\E[1;3C,
+	kRIT4=\E[1;4C,
+	kRIT5=\E[1;5C,
+	kRIT6=\E[1;6C,
+	kRIT7=\E[1;7C,
+	kUP=\E[1;2A,
+	kUP3=\E[1;3A,
+	kUP4=\E[1;4A,
+	kUP5=\E[1;5A,
+	kUP6=\E[1;6A,
+	kUP7=\E[1;7A,
+	rmxx=\E[29m,
+	smxx=\E[9m,
```

**Comment by lbschenkel** [comment]
I have later found out that to trigger the assertion error when invoking `nvim`, I need *both* the following lines present in `init.vim`:
```
set colorcolumn=80
set termguicolors
```
Invoking `nvim -u NORC` or with just one of the two lines above in `init.vim` the assertion error does not happen. I have filed a bug in NeoVim as well: https://github.com/neovim/neovim/issues/7206

**Comment by fornwall** [comment]
See my comment at https://github.com/neovim/neovim/issues/7206 why I believe that this is a neovim issue and not a libunibilium one.

**Comment by lbschenkel** [comment]
I'm closing this since it became clear this is a NeoVim bug. Apologies for the spurious report.
