### ISSUE TITLE
Can't load xterm-256color since ncurses 6.1

### ISSUE THREAD

**Issue by yan12125** [mauke/unibilium#30]
Arch Linux recently upgraded ncurses from 6.0+20170902 to 6.1, and I noticed that unibilium can no longer load xterm-256color.

Here's a testing program:
```C
#include <unibilium.h>

int main(int argc, char *argv[])
{
    if (argc != 2) {
        return 1;
    }
    unibi_term *term = unibi_from_file(argv[1]);
    if (!term) {
        perror("unibilium_from_file");
        return 1;
    }
    unibi_destroy(term);
    return 0;
}
```
With 6.0+20170902, both of the follow commands run fine:
```
$ ./a.out /usr/share/terminfo/x/xterm
$ ./a.out /usr/share/terminfo/x/xterm-256color
```
With ncurses 6.1, xterm-256color fails:
```
$ ./a.out /usr/share/terminfo/x/xterm
$ ./a.out /usr/share/terminfo/x/xterm-256color
unibilium_from_file: Invalid argument
```

I noticed this when debugging https://github.com/neovim/neovim/issues/7932 on xfce4-terminal, which uses xterm-256color as $TERM.

**Comment by yan12125** [comment]
Turns out that ncurses 6.0-20180121 defines a new magic number 01036 

https://github.com/ThomasDickey/ncurses-snapshots/commit/7ac78d357c4ea2d4199a742b195eb4a8ce8dad55#diff-2c0786db969084ba9e087d82f8275e0bR85

**Comment by mauke** [comment]
I've implemented support for this new format in https://github.com/mauke/unibilium/tree/wide-int. The changes are not quite backwards compatible (`short` turns into `int` everywhere).

I'm probably going to release this as a new major version later.

**Comment by fornwall** [comment]
Version 2.0 of unibilium has been released, so I guess this issue can be closed?

**Comment by yan12125** [comment]
> Version 2.0 of unibilium has been released, so I guess this issue can be closed?

Yes! Thanks for the awesome work @mauke!
