### ISSUE TITLE
crash produced by neovim with st-256color

### ISSUE THREAD

**Issue by ghost** [mauke/unibilium#32]
This program produces the exact same crash I reported in #31. I am just a neovim user, I don't understand what these functions do. I only extracted the fmt from the crash and set some params, so there are valid pointers. I also don't know if it is somehow neovims fault producing bad input. I put this extra effort in, because @justinmk pointed out, it might still be an unibilium bug.

```c
#include <unibilium.h>

int main(void) {
    char buf[4096];
    unibi_var_t param[9];
    param[0] = unibi_var_from_str("str");
    param[1] = unibi_var_from_str("str");
    param[2] = unibi_var_from_str("str");
    unibi_run("\033]52;%p1%s;%p2%s\a", param, buf, 4096);
    return 0;
}
```

**Comment by ganwell** [comment]
I built latest and it works.

**Comment by ganwell** [comment]
Sorry not true. Latest fails too.

**Comment by ghost** [comment]
I built latest from source and the program works.
