### ISSUE TITLE
Can't find terminfo entries on OSX

### ISSUE THREAD

**Issue by tarruda** [mauke/unibilium#6]
Here's the output of `ls /usr/share/terminfo` on linux :
```
1  2  3  4  5  6  7  8  9  a  A  b  c  d  e  E  f  g  h  i  j  k  l  L  m  M  n  N  o  p  P  q  Q  r  s  t  u  v  w  x  X  z
```

and here's for OSX: 

```
31 32 33 34 35 36 37 38 39 41 45 4c 4d 4e 50 51 58 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 70 71 72 73 74 75 76 77 78 7a
```

Is this a possible reason for unibilium not finding the entries on OSX? Yet the normal terminfo commands have no trouble in finding them(infocmp, tput, ...)

**Comment by mauke** [comment]
> Is this a possible reason for unibilium not finding the entries on OSX?

Yes.

**Comment by tarruda** [comment]
Do you think OSX ships a propriety terminfo implementation? If so, do you have any ideas of how we may add OSX support to unibilium?

**Comment by mauke** [comment]
Just pushed https://github.com/mauke/unibilium/commit/bb979ff6f66a18663e15d086dec6276561b86ee0. I don't have OS X. Can you check if this fixes the issue?

**Comment by tarruda** [comment]
> Just pushed bb979ff. I don't have OS X. Can you check if this fixes the issue?

Thank you, I will check as soon as I get to my computer

**Comment by tarruda** [comment]
Its working, thanks again
