### ISSUE TITLE
License clarification for tools/

### ISSUE THREAD

**Issue by jamessan** [mauke/unibilium#9]
The LICENSE file and most files refer to their license as LGPL-3+.  However, `tools/` has two outliers–unibi-dump.c ("public domain") and gen-static-test.c (GPL-3+).  I just wanted to clarify that these are correct, as I'm preparing to upload a package to Debian.

Cheers,
James

**Comment by mauke** [comment]
Thanks for bringing this to my attention. I'm about to change the license on these files.

Note that `gen-static-test.c` is not meant to be installed (it was used to generate/update test files in `t/`). `unibi-dump` and `unibi-put` are potentially useful but the Makefile currently does nothing with them.

**Comment by mauke** [comment]
I think MIT is acceptable/fairly lenient, so I'm closing this issue. If there are still problems, feel free to reopen this issue (does github allow this?) or create a new one.
